### PR TITLE
Fix compile breaking syntax error

### PR DESCRIPTION
**Pull request by NeoN2k**

### CODE REVIEW

**Comment by Smegheid** [comment]
Good to know I'm not the only one! I used the 2004-era version of sunwait for a very long time, and only recently decided to try it out somewhere else for another project. I discovered that it had moved on and now exists here on github, cloned the current version from master, and ran straight into this same thing.

I came to the same conclusion as this patch, and the end result seems to work just fine.

**Comment by gilesorr** [comment]
I was just about to submit the same pull request when sunwait wouldn't build on Raspberry Pi OS or Fedora.  I hope this is merged soon.

**Comment by mandulaj** [comment]
Yes  please! Was going to submit one as well.

**Comment by RikiReal** [comment]
I wish I had seen this sooner. Well, hindsight is 20-20!

**Review by nigels-com — APPROVED** [review]

**Comment by risacher** [comment]
Closing this and thanks to all that noticed the error.  Special thanks to Alan Prescot who somehow managed to get my attention enough to actually fix it.

**Pull request closed without merging**
